import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import SessionWrapper from "@/app/component/SessionWrapper";
import Footer from "@/components/Footer";
import { CartProvider } from "@/context/CartContext";
import CartPopup from "@/components/CartPopup";
import ChatBubble from "@/components/ChatBubble";

const inter = Inter({ subsets: ["latin"] });


export const metadata = {
  title: "Pizza Logist",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {


  return (
    <html lang="en">

      <SessionWrapper>
        <body className=" bg-white">
          <CartProvider>
            <Navbar />
            <CartPopup />
            <ChatBubble />
            <div >
              {children}
              <script src="https://cdn.lordicon.com/lordicon.js"></script>
              <Footer />
            </div>
          </CartProvider>
        </body>
      </SessionWrapper>

    </html >
  );
}
